"""empty message

Revision ID: 89148162102e
Revises: 
Create Date: 2021-03-13 13:44:42.893702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89148162102e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('podcast',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('uploadtime', sa.DateTime(), nullable=True),
    sa.Column('host', sa.String(length=100), nullable=True),
    sa.Column('Participants', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Participants'),
    sa.UniqueConstraint('host'),
    sa.UniqueConstraint('name')
    )
    op.create_table('song',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('uploadtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('song')
    op.drop_table('podcast')
    # ### end Alembic commands ###
